/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grginventory;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.JTable;
import javax.swing.*;
import java.awt.event.*;
import java.awt.*;
import java.awt.print.*;
import java.sql.Statement;
import java.text.*;
import javax.swing.table.DefaultTableModel;
import javax.print.PrintException;
import javax.swing.JFrame;
/**
 *
 * @author gaming
 */
public class parts_io extends javax.swing.JFrame {
    Connection conn         = null;
    ResultSet rs            = null;
    PreparedStatement pst   = null;
    /**
     * Creates new form parts_io
     */
    public parts_io() {
        initComponents();
        try {
            conn = koneksi.wijoyokonek();
            show_data();
            show_data2();
            load_part_number();
            load_partner();
            kdin.setVisible(false);
            kdpartnerr.setVisible(false);
            plus.setVisible(false);
            kdout.setVisible(false);
            plus2.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(parts_io.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void show_data(){
        String perintah = "SELECT * FROM  parts_in";
        try {
            pst = conn.prepareStatement(perintah);
            rs = pst.executeQuery();
            
            DefaultTableModel makan = new DefaultTableModel();
            makan.addColumn("In Codes");
            makan.addColumn("Date In");
            makan.addColumn("Quantity");
            makan.addColumn("Part Number");
            makan.addColumn("Partner Code");
            makan.addColumn("Status");
        while (rs.next()){
            makan.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6)});
        }
        partsin.setModel(makan);
        } catch (SQLException ex) {
            
        }
    }
    
    private void show_data2(){
        String perintah = "SELECT * FROM  parts_out";
        try {
            pst = conn.prepareStatement(perintah);
            rs = pst.executeQuery();
            
            DefaultTableModel makan = new DefaultTableModel();
            makan.addColumn("Out Codes");
            makan.addColumn("Part Number");
            makan.addColumn("Date Out");
            makan.addColumn("Quantity");
            makan.addColumn("Status");
        while (rs.next()){
            makan.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5)});
        }
        partsout.setModel(makan);
        } catch (SQLException ex) {
            
        }
    }
    
    private void clear(){
        
        cbpartner.setSelectedItem(null);
        cbnumber.setSelectedItem(null);
        cbstatus.setSelectedItem(null);
        qty.setText("");
        kdin.setText("");
        kdpartnerr.setText("");
        firstqty.setText("");
        plus.setText("");
        datein.setDate(null);
    }
    
    private void clear2(){
        
        qty2.setText("");
        kdout.setText("");
        firstqty2.setText("");
        plus2.setText("");
        cbnumber2.setSelectedItem(null);
        cbstatus2.setSelectedItem(null);
        dateout.setDate(null);
    }
    
    private void load_part_number(){
        try {
            Statement cs = conn.createStatement();
            ResultSet rs = cs.executeQuery("select * from parts_stock");
            while (rs.next()) {
                String item = rs.getString("part_number");
                cbnumber.addItem(item);
                cbnumber2.addItem(item);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        
    
}
    
    private void load_partner(){
        try {
            Statement cs = conn.createStatement();
            ResultSet rs = cs.executeQuery("select * from partner");
            while (rs.next()) {
                String item = rs.getString("Partner_name");
                cbpartner.addItem(item);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        apa = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btnclear = new javax.swing.JButton();
        btnadd = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        partsin = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cbpartner = new javax.swing.JComboBox<>();
        cbstatus = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        datein = new com.toedter.calendar.JDateChooser();
        jLabel19 = new javax.swing.JLabel();
        qty = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        cbnumber = new javax.swing.JComboBox<>();
        kdin = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        firstqty = new javax.swing.JTextField();
        kdpartnerr = new javax.swing.JTextField();
        plus = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        apa2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btnclear2 = new javax.swing.JButton();
        btnadd2 = new javax.swing.JButton();
        btnedit2 = new javax.swing.JButton();
        btndelete2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        partsout = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        cbstatus2 = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        dateout = new com.toedter.calendar.JDateChooser();
        jLabel30 = new javax.swing.JLabel();
        qty2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        cbnumber2 = new javax.swing.JComboBox<>();
        kdout = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        firstqty2 = new javax.swing.JTextField();
        plus2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(27, 30, 73));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel7.setText("Parts In/Out");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 150, 70));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grginventory/image/enlogo.png"))); // NOI18N
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 70));

        jPanel4.setBackground(new java.awt.Color(27, 30, 73));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 10, 90));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel11.setText("X");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel11MouseEntered(evt);
            }
        });
        jLabel11.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel11FocusGained(evt);
            }
        });
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, -1, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel10.setText("?");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, -1, -1));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel12.setText("-");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 70));

        apa.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(27, 62, 74));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Actions");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, 30));

        btnclear.setBackground(new java.awt.Color(0, 162, 231));
        btnclear.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnclear.setForeground(new java.awt.Color(255, 255, 255));
        btnclear.setText("Clear");
        btnclear.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnclear.setBorderPainted(false);
        btnclear.setFocusPainted(false);
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        jPanel5.add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 110, 40));

        btnadd.setBackground(new java.awt.Color(0, 162, 231));
        btnadd.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnadd.setForeground(new java.awt.Color(255, 255, 255));
        btnadd.setText("Submit");
        btnadd.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnadd.setBorderPainted(false);
        btnadd.setFocusPainted(false);
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        jPanel5.add(btnadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 110, 40));

        btnedit.setBackground(new java.awt.Color(0, 162, 231));
        btnedit.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnedit.setForeground(new java.awt.Color(255, 255, 255));
        btnedit.setText("Change");
        btnedit.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnedit.setBorderPainted(false);
        btnedit.setFocusPainted(false);
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });
        jPanel5.add(btnedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 110, 40));

        btndelete.setBackground(new java.awt.Color(0, 162, 231));
        btndelete.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btndelete.setForeground(new java.awt.Color(255, 255, 255));
        btndelete.setText("Delete");
        btndelete.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btndelete.setBorderPainted(false);
        btndelete.setFocusPainted(false);
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        jPanel5.add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 110, 40));

        partsin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        partsin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                partsinMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(partsin);

        jLabel15.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel15.setText("Part Number :");

        jLabel16.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel16.setText("Partner :");

        cbpartner.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbpartnerItemStateChanged(evt);
            }
        });

        cbstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GOOD", "DEFECT" }));

        jLabel17.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel17.setText("Status :");

        jLabel18.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel18.setText("Date In :");

        datein.setDateFormatString("yyyy-MM-dd");

        jLabel19.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel19.setText("Quantity :");

        qty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyActionPerformed(evt);
            }
        });

        jLabel1.setText("OR");

        jButton1.setText("New");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cbnumber.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbnumberItemStateChanged(evt);
            }
        });

        kdin.setEnabled(false);

        jLabel20.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel20.setText("Current Quantity :");

        firstqty.setEnabled(false);

        kdpartnerr.setEnabled(false);

        plus.setEnabled(false);

        javax.swing.GroupLayout apaLayout = new javax.swing.GroupLayout(apa);
        apa.setLayout(apaLayout);
        apaLayout.setHorizontalGroup(
            apaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(apaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(apaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(apaLayout.createSequentialGroup()
                        .addGroup(apaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, apaLayout.createSequentialGroup()
                                .addGroup(apaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(apaLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(32, 32, 32)))
                        .addGroup(apaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(qty, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(apaLayout.createSequentialGroup()
                                .addGroup(apaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cbpartner, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbnumber, javax.swing.GroupLayout.Alignment.LEADING, 0, 80, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)))
                        .addGap(18, 18, 18)
                        .addGroup(apaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(apaLayout.createSequentialGroup()
                                .addGroup(apaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(apaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(datein, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                    .addComponent(cbstatus, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(apaLayout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(firstqty)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(apaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(apaLayout.createSequentialGroup()
                                .addComponent(kdin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kdpartnerr, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(plus))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        apaLayout.setVerticalGroup(
            apaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, apaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(apaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(apaLayout.createSequentialGroup()
                        .addGroup(apaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(apaLayout.createSequentialGroup()
                                .addGroup(apaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel1)
                                    .addComponent(jButton1)
                                    .addComponent(cbnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(apaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(cbpartner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(apaLayout.createSequentialGroup()
                                .addGroup(apaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(cbstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kdin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kdpartnerr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(apaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(apaLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(apaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel18)
                                            .addComponent(datein, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(apaLayout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(plus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addGroup(apaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addComponent(firstqty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Data In", apa);

        apa2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel8.setBackground(new java.awt.Color(27, 62, 74));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Actions");
        jPanel8.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, 30));

        btnclear2.setBackground(new java.awt.Color(0, 162, 231));
        btnclear2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnclear2.setForeground(new java.awt.Color(255, 255, 255));
        btnclear2.setText("Clear");
        btnclear2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnclear2.setBorderPainted(false);
        btnclear2.setFocusPainted(false);
        btnclear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclear2ActionPerformed(evt);
            }
        });
        jPanel8.add(btnclear2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 110, 40));

        btnadd2.setBackground(new java.awt.Color(0, 162, 231));
        btnadd2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnadd2.setForeground(new java.awt.Color(255, 255, 255));
        btnadd2.setText("Submit");
        btnadd2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnadd2.setBorderPainted(false);
        btnadd2.setFocusPainted(false);
        btnadd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadd2ActionPerformed(evt);
            }
        });
        jPanel8.add(btnadd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 110, 40));

        btnedit2.setBackground(new java.awt.Color(0, 162, 231));
        btnedit2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnedit2.setForeground(new java.awt.Color(255, 255, 255));
        btnedit2.setText("Change");
        btnedit2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnedit2.setBorderPainted(false);
        btnedit2.setFocusPainted(false);
        btnedit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnedit2ActionPerformed(evt);
            }
        });
        jPanel8.add(btnedit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 110, 40));

        btndelete2.setBackground(new java.awt.Color(0, 162, 231));
        btndelete2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btndelete2.setForeground(new java.awt.Color(255, 255, 255));
        btndelete2.setText("Delete");
        btndelete2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btndelete2.setBorderPainted(false);
        btndelete2.setFocusPainted(false);
        btndelete2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelete2ActionPerformed(evt);
            }
        });
        jPanel8.add(btndelete2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 110, 40));

        partsout.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        partsout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                partsoutMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(partsout);

        jLabel22.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel22.setText("Part Number :");

        cbstatus2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GOOD", "DEFECT" }));

        jLabel28.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel28.setText("Status :");

        jLabel29.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel29.setText("Date Out :");

        dateout.setDateFormatString("yyyy-MM-dd");

        jLabel30.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel30.setText("Quantity :");

        qty2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qty2ActionPerformed(evt);
            }
        });

        jLabel3.setText("OR");

        jButton3.setText("New");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        cbnumber2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbnumber2ItemStateChanged(evt);
            }
        });

        kdout.setEnabled(false);

        jLabel31.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel31.setText("Current Quantity :");

        firstqty2.setEnabled(false);

        plus2.setEnabled(false);

        javax.swing.GroupLayout apa2Layout = new javax.swing.GroupLayout(apa2);
        apa2.setLayout(apa2Layout);
        apa2Layout.setHorizontalGroup(
            apa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(apa2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(apa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(apa2Layout.createSequentialGroup()
                        .addGroup(apa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(apa2Layout.createSequentialGroup()
                                .addGroup(apa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, apa2Layout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(apa2Layout.createSequentialGroup()
                                        .addComponent(jLabel30)
                                        .addGap(32, 32, 32)))
                                .addGroup(apa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(apa2Layout.createSequentialGroup()
                                        .addComponent(cbnumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton3))
                                    .addComponent(qty2)))
                            .addGroup(apa2Layout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(firstqty2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(apa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(apa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dateout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbstatus2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kdout, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(plus2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        apa2Layout.setVerticalGroup(
            apa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, apa2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(apa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(apa2Layout.createSequentialGroup()
                        .addGroup(apa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(apa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel31)
                                .addComponent(firstqty2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(apa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(apa2Layout.createSequentialGroup()
                                    .addGroup(apa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel28)
                                        .addComponent(cbstatus2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(kdout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(plus2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(apa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel29)
                                        .addComponent(dateout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(apa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel3)
                                    .addComponent(jButton3)
                                    .addComponent(cbnumber2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(apa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(qty2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 791, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(apa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 532, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(apa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Data Out", jPanel6);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 790, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseEntered

    private void jLabel11FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel11FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11FocusGained

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnclearActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        try {
                    String query = "INSERT INTO parts_in (kd_in, date_in, qty, part_number, kd_partner, status) value(?,?,?,?,?,?)";
                    pst = conn.prepareStatement(query);
               
                    pst.setString(1, null);
                    pst.setString(2, ((JTextField)datein.getDateEditor().getUiComponent()).getText());
                    pst.setString(3, qty.getText());
               
                    String value=cbnumber.getSelectedItem().toString();
                    pst.setString(4, value);
                    
                    pst.setString(5, kdpartnerr.getText());
                    
                    String value2=cbstatus.getSelectedItem().toString();
                    pst.setString(6, value2);
                    
                    pst.execute();
                    
                    
                    //////////////////////////////////////////////////////////////////Update QTY////////////////////////////////////////
                    String sql = "UPDATE parts_stock SET total_qty=? where part_number='"+cbnumber.getSelectedItem()+"'";
                    pst = conn.prepareStatement(sql);
                    pst.setString(1, plus.getText());
                    pst.execute();
                    /////////////////////////////////////////////////////////////////////////////////////////////////////////
                    JOptionPane.showMessageDialog(null, "Data Berhasil  Ditambah");
                    show_data();
                    clear();
                    
        } catch (SQLException ex) {
            Logger.getLogger(parts.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnaddActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
        try {
                    String sql = "UPDATE parts_in SET date_in=?, qty=?, part_number=?, kd_partner=?, status=? where kd_in='"+kdin.getText()+"'";
                    pst = conn.prepareStatement(sql);
                
                    
                    pst.setString(1, ((JTextField)datein.getDateEditor().getUiComponent()).getText());
                    pst.setString(2, qty.getText());
               
                    String value=cbnumber.getSelectedItem().toString();
                    pst.setString(3, value);
                    
                    
                    pst.setString(4, kdpartnerr.getText());
                    
                    String value2=cbstatus.getSelectedItem().toString();
                    pst.setString(5, value);
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "Data Berhasil Diupdate");
                    show_data();
                    clear();
        } catch (SQLException ex) {
            Logger.getLogger(parts.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btneditActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        try {
        String sql = "DELETE FROM parts_in where kd_in = ?";
        pst = conn.prepareStatement(sql);
            pst.setString(1, kdin.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Successfuly Deleted");
            show_data();
        } catch (SQLException ex) {
            Logger.getLogger(parts.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void partsinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_partsinMouseClicked
        // TODO add your handling code here:
        int row = partsin.getSelectedRow();
        String diklik = (partsin.getModel().getValueAt(row, 0).toString());
        String sql = "SELECT * FROM parts_in WHERE kd_in='"+diklik+"'";

        try {
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

            if((rs.next())){
                
                String tambah2 = rs.getString("kd_in");
                kdin.setText(tambah2);
                String tambah1 = rs.getString("qty");
                qty.setText(tambah1);
                String tambah11 = rs.getString("date_in");
                ((JTextField)datein.getDateEditor().getUiComponent()).setText(tambah11);
                
                String item2 = rs.getString("status");
                cbstatus.setSelectedItem(item2);
                String item = rs.getString("part_number");
                cbnumber.setSelectedItem(item);
            }
            /////////////////////////////////////cek stock//////////////////////
            String diklik2 = (partsin.getModel().getValueAt(row, 3).toString());
            String sql2 = "SELECT * FROM parts_stock WHERE part_number='"+diklik2+"'";
            pst = conn.prepareStatement(sql2);
            rs = pst.executeQuery();
            if((rs.next())){
                String tambah2 = rs.getString("total_qty");
                firstqty.setText(tambah2);    
            }
            ////////////////////////////////////////////////////////////////////
            String diklik3 = (partsin.getModel().getValueAt(row, 5).toString());
            String sql3 = "SELECT * FROM partner WHERE kd_partner='"+diklik3+"'";
            pst = conn.prepareStatement(sql3);
            rs = pst.executeQuery();
            if((rs.next())){
                String item1 = rs.getString("kd_partner");
                cbpartner.setSelectedItem(item1); 
            }
            ////////////////////////////////////////////////////////////////////
        } catch (SQLException ex) {
            Logger.getLogger(parts_io.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_partsinMouseClicked

    private void cbnumberItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbnumberItemStateChanged
        // TODO add your handling code here:
            
        try {
            String diklik2 = cbnumber.getSelectedItem().toString();
            String sql2 = "SELECT * FROM parts_stock WHERE part_number='"+diklik2+"'";
            pst = conn.prepareStatement(sql2);
            rs = pst.executeQuery();
            if((rs.next())){
            String tambah2 = rs.getString("total_qty");
            firstqty.setText(tambah2); 
            }
        } catch (SQLException ex) {
            Logger.getLogger(parts_io.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_cbnumberItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        parts partsio = new parts();
        partsio.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbpartnerItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbpartnerItemStateChanged
        // TODO add your handling code here:
        try {
            String diklik2 = cbpartner.getSelectedItem().toString();
            String sql2 = "SELECT * FROM partner WHERE Partner_name='"+diklik2+"'";
            pst = conn.prepareStatement(sql2);
            rs = pst.executeQuery();
            if((rs.next())){
            String tambah2 = rs.getString("kd_partner");
            kdpartnerr.setText(tambah2); 
            }
        } catch (SQLException ex) {
            Logger.getLogger(parts_io.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cbpartnerItemStateChanged

    private void qtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyActionPerformed
        // TODO add your handling code here:
        int awal,tambah,hasil;
        awal = Integer.parseInt(firstqty.getText());
        tambah = Integer.parseInt(qty.getText());
        hasil = awal + tambah;
        plus.setText(Integer.toString(hasil));
    }//GEN-LAST:event_qtyActionPerformed

    private void cbnumber2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbnumber2ItemStateChanged
        // TODO add your handling code here:
         try {
            String diklik2 = cbnumber2.getSelectedItem().toString();
            String sql2 = "SELECT * FROM parts_stock WHERE part_number='"+diklik2+"'";
            pst = conn.prepareStatement(sql2);
            rs = pst.executeQuery();
            if((rs.next())){
            String tambah2 = rs.getString("total_qty");
            firstqty2.setText(tambah2); 
            }
        } catch (SQLException ex) {
            Logger.getLogger(parts_io.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cbnumber2ItemStateChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void qty2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qty2ActionPerformed
        // TODO add your handling code here:
        int awal,tambah,hasil;
        awal = Integer.parseInt(firstqty2.getText());
        tambah = Integer.parseInt(qty2.getText());
        hasil = awal - tambah;
        plus2.setText(Integer.toString(hasil));
    }//GEN-LAST:event_qty2ActionPerformed

    private void partsoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_partsoutMouseClicked
        // TODO add your handling code here:
        int row = partsout.getSelectedRow();
        String diklik = (partsout.getModel().getValueAt(row, 0).toString());
        String sql = "SELECT * FROM parts_out WHERE kd_out='"+diklik+"'";

        try {
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

            if((rs.next())){
                
                String tambah2 = rs.getString("kd_out");
                kdout.setText(tambah2);
                String tambah1 = rs.getString("qty");
                qty2.setText(tambah1);
                String tambah11 = rs.getString("date_out");
                ((JTextField)dateout.getDateEditor().getUiComponent()).setText(tambah11);
                
                String item2 = rs.getString("status");
                cbstatus2.setSelectedItem(item2);
                String item = rs.getString("part_number");
                cbnumber2.setSelectedItem(item);
            }
            /////////////////////////////////////cek stock//////////////////////
            String diklik2 = (partsout.getModel().getValueAt(row, 2).toString());
            String sql2 = "SELECT * FROM parts_stock WHERE part_number='"+diklik2+"'";
            pst = conn.prepareStatement(sql2);
            rs = pst.executeQuery();
            if((rs.next())){
                String tambah2 = rs.getString("total_qty");
                firstqty2.setText(tambah2);    
            }
            ////////////////////////////////////////////////////////////////////
        } catch (SQLException ex) {
            Logger.getLogger(parts_io.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_partsoutMouseClicked

    private void btndelete2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelete2ActionPerformed
        // TODO add your handling code here:
        try {
        String sql = "DELETE FROM parts_out where kd_out = ?";
        pst = conn.prepareStatement(sql);
            pst.setString(1, kdout.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Successfuly Deleted");
            show_data2();
            clear2();
        } catch (SQLException ex) {
            Logger.getLogger(parts.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btndelete2ActionPerformed

    private void btnedit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnedit2ActionPerformed
        // TODO add your handling code here:
        try {
                    String sql = "UPDATE parts_out SET date_out=?, qty=?, part_number=?, status=? where kd_out='"+kdout.getText()+"'";
                    pst = conn.prepareStatement(sql);
                
                    
                    pst.setString(1, ((JTextField)dateout.getDateEditor().getUiComponent()).getText());
                    pst.setString(2, qty2.getText());
               
                    String value=cbnumber2.getSelectedItem().toString();
                    pst.setString(3, value);
                    
                    String value2=cbstatus2.getSelectedItem().toString();
                    pst.setString(4, value);
                    
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "Data Berhasil Diupdate");
                    show_data2();
                    clear2();
        } catch (SQLException ex) {
            Logger.getLogger(parts.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnedit2ActionPerformed

    private void btnadd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadd2ActionPerformed
        // TODO add your handling code here:
        try {
                    String query = "INSERT INTO parts_out (kd_out, part_number, date_out, qty, status) value(?,?,?,?,?)";
                    pst = conn.prepareStatement(query);
               
                    pst.setString(1, null);
                    String value=cbnumber2.getSelectedItem().toString();
                    pst.setString(2, value);
                    pst.setString(3, ((JTextField)dateout.getDateEditor().getUiComponent()).getText());
                    pst.setString(4, qty2.getText());
               
                    String value2=cbstatus2.getSelectedItem().toString();
                    pst.setString(5, value2);
                    
                    pst.execute();
                    
                    
                    //////////////////////////////////////////////////////////////////Update QTY////////////////////////////////////////
                    String sql = "UPDATE parts_stock SET total_qty=? where part_number='"+cbnumber2.getSelectedItem()+"'";
                    pst = conn.prepareStatement(sql);
                    pst.setString(1, plus2.getText());
                    pst.execute();
                    /////////////////////////////////////////////////////////////////////////////////////////////////////////
                    JOptionPane.showMessageDialog(null, "Data Berhasil  Ditambah");
                    show_data2();
                    clear2();
                    
        } catch (SQLException ex) {
            Logger.getLogger(parts.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnadd2ActionPerformed

    private void btnclear2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclear2ActionPerformed
        // TODO add your handling code here:
        clear2();
    }//GEN-LAST:event_btnclear2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(parts_io.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(parts_io.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(parts_io.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(parts_io.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new parts_io().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel apa;
    private javax.swing.JPanel apa2;
    public javax.swing.JButton btnadd;
    public javax.swing.JButton btnadd2;
    public javax.swing.JButton btnclear;
    public javax.swing.JButton btnclear2;
    public javax.swing.JButton btndelete;
    public javax.swing.JButton btndelete2;
    public javax.swing.JButton btnedit;
    public javax.swing.JButton btnedit2;
    private javax.swing.JComboBox<String> cbnumber;
    private javax.swing.JComboBox<String> cbnumber2;
    private javax.swing.JComboBox<String> cbpartner;
    private javax.swing.JComboBox<String> cbstatus;
    private javax.swing.JComboBox<String> cbstatus2;
    private com.toedter.calendar.JDateChooser datein;
    private com.toedter.calendar.JDateChooser dateout;
    private javax.swing.JTextField firstqty;
    private javax.swing.JTextField firstqty2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField kdin;
    private javax.swing.JTextField kdout;
    private javax.swing.JTextField kdpartnerr;
    private javax.swing.JTable partsin;
    private javax.swing.JTable partsout;
    private javax.swing.JTextField plus;
    private javax.swing.JTextField plus2;
    private javax.swing.JTextField qty;
    private javax.swing.JTextField qty2;
    // End of variables declaration//GEN-END:variables
}
